# Generated by Django 5.2.6 on 2025-11-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_masternewspost_exclude_portal_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdistribution',
            name='edit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsdistribution',
            name='edited_image',
            field=models.ImageField(blank=True, help_text='Edited image for this portal-specific distribution.', null=True, upload_to='distribution_edits/%Y/%m/%d/'),
        ),
    ]
